name: 00 - Main CI / CD Pipeline
on:
  push:
    branches: ["main"]
    paths-ignore:
      -'**/*.md'
      -'**/*.txt'
  workflow_dispatch:

permissions: 
  checks: write
  issues: read
  pull-requests: write

jobs:
  build: 
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit
  

      
